table 'Dim Geography'

	column 'Geography Key'
		dataType: int64
		isHidden
		sourceColumn: geography_key

	column 'Geography Type'
		dataType: string
		sourceColumn: geography_type

	column 'State Code'
		dataType: string
		sourceColumn: state_code

	column 'Geography Name'
		dataType: string
		sourceColumn: geography_name

	partition 'Dim Geography' = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        File.Contents("C:\Users\10619\Documents\Projects\provider-payer-quality-reporting\data\processed\powerbi_import\dim_geography.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    PromotedHeaders = Table.PromoteHeaders(
				        Source,
				        [PromoteAllScalars=true]
				    ),
				    TypedColumns = Table.TransformColumnTypes(
				        PromotedHeaders,
				        {{"geography_key", Int64.Type}, {"geography_type", type text}, {"state_code", type text}, {"geography_name", type text}},
				        "en-US"
				    )
				in
				    TypedColumns

