table 'Fact State Benchmark'

	column 'State Benchmark Key'
		dataType: int64
		isHidden
		sourceColumn: state_benchmark_key

	column 'Geography Key'
		dataType: int64
		isHidden
		sourceColumn: geography_key

	column 'Measure Key'
		dataType: int64
		isHidden
		sourceColumn: measure_key

	column 'Reporting Period Key'
		dataType: int64
		isHidden
		sourceColumn: reporting_period_key

	column 'Source Release Key'
		dataType: int64
		isHidden
		sourceColumn: source_release_key

	column 'Hospitals Worse'
		dataType: int64
		summarizeBy: sum
		sourceColumn: hospitals_worse

	column 'Hospitals Same'
		dataType: int64
		summarizeBy: sum
		sourceColumn: hospitals_same

	column 'Hospitals Better'
		dataType: int64
		summarizeBy: sum
		sourceColumn: hospitals_better

	column 'Hospitals Too Few'
		dataType: int64
		summarizeBy: sum
		sourceColumn: hospitals_too_few

	column 'Footnote Code'
		dataType: string
		sourceColumn: footnote_code_raw

	partition 'Fact State Benchmark' = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        File.Contents("C:\Users\10619\Documents\Projects\provider-payer-quality-reporting\data\processed\powerbi_import\fact_provider_state_benchmark.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    PromotedHeaders = Table.PromoteHeaders(
				        Source,
				        [PromoteAllScalars=true]
				    ),
				    TypedColumns = Table.TransformColumnTypes(
				        PromotedHeaders,
				        {{"state_benchmark_key", Int64.Type}, {"geography_key", Int64.Type}, {"measure_key", Int64.Type}, {"reporting_period_key", Int64.Type}, {"source_release_key", Int64.Type}, {"hospitals_worse", Int64.Type}, {"hospitals_same", Int64.Type}, {"hospitals_better", Int64.Type}, {"hospitals_too_few", Int64.Type}, {"footnote_code_raw", type text}},
				        "en-US"
				    )
				in
				    TypedColumns

