table 'Fact HVBP'

	measure 'Selected HVBP TPS' = IF(SELECTEDVALUE('Fact HVBP'[TPS Reportable]) = TRUE(), SELECTEDVALUE('Fact HVBP'[Total Performance Score]), BLANK())
		formatString: 0.00

	column 'Provider Program Score Key'
		dataType: int64
		isHidden
		sourceColumn: provider_program_score_key

	column 'Facility Key'
		dataType: int64
		isHidden
		sourceColumn: facility_key

	column 'Reporting Period Key'
		dataType: int64
		isHidden
		sourceColumn: reporting_period_key

	column 'Source Release Key'
		dataType: int64
		isHidden
		sourceColumn: source_release_key

	column 'Fiscal Year'
		dataType: int64
		summarizeBy: none
		sourceColumn: fiscal_year

	column 'Clinical Outcomes Unweighted'
		dataType: double
		summarizeBy: none
		sourceColumn: clinical_outcomes_unweighted

	column 'Clinical Outcomes Weighted'
		dataType: double
		summarizeBy: none
		sourceColumn: clinical_outcomes_weighted

	column 'Engagement Unweighted'
		dataType: double
		summarizeBy: none
		sourceColumn: engagement_unweighted

	column 'Engagement Weighted'
		dataType: double
		summarizeBy: none
		sourceColumn: engagement_weighted

	column 'Safety Unweighted'
		dataType: double
		summarizeBy: none
		sourceColumn: safety_unweighted

	column 'Safety Weighted'
		dataType: double
		summarizeBy: none
		sourceColumn: safety_weighted

	column 'Efficiency Unweighted'
		dataType: double
		summarizeBy: none
		sourceColumn: efficiency_unweighted

	column 'Efficiency Weighted'
		dataType: double
		summarizeBy: none
		sourceColumn: efficiency_weighted

	column 'Total Performance Score'
		dataType: double
		summarizeBy: none
		sourceColumn: total_performance_score

	column 'TPS Reportable'
		dataType: boolean
		sourceColumn: is_tps_reportable

	column 'Suppression Reason'
		dataType: string
		sourceColumn: suppression_reason

	partition 'Fact HVBP' = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        File.Contents("C:\Users\10619\Documents\Projects\provider-payer-quality-reporting\data\processed\powerbi_import\fact_provider_program_score.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    PromotedHeaders = Table.PromoteHeaders(
				        Source,
				        [PromoteAllScalars=true]
				    ),
				    TypedColumns = Table.TransformColumnTypes(
				        PromotedHeaders,
				        {{"provider_program_score_key", Int64.Type}, {"facility_key", Int64.Type}, {"reporting_period_key", Int64.Type}, {"source_release_key", Int64.Type}, {"fiscal_year", Int64.Type}, {"clinical_outcomes_unweighted", type number}, {"clinical_outcomes_weighted", type number}, {"engagement_unweighted", type number}, {"engagement_weighted", type number}, {"safety_unweighted", type number}, {"safety_weighted", type number}, {"efficiency_unweighted", type number}, {"efficiency_weighted", type number}, {"total_performance_score", type number}, {"is_tps_reportable", type logical}, {"suppression_reason", type text}},
				        "en-US"
				    )
				in
				    TypedColumns

