table 'Fact National Benchmark'

	measure 'Selected National Benchmark' = SELECTEDVALUE('Fact National Benchmark'[National Rate])
		formatString: 0.00

	column 'National Benchmark Key'
		dataType: int64
		isHidden
		sourceColumn: national_benchmark_key

	column 'Measure Key'
		dataType: int64
		isHidden
		sourceColumn: measure_key

	column 'Reporting Period Key'
		dataType: int64
		isHidden
		sourceColumn: reporting_period_key

	column 'Source Release Key'
		dataType: int64
		isHidden
		sourceColumn: source_release_key

	column 'National Rate'
		dataType: double
		summarizeBy: none
		sourceColumn: national_rate_numeric

	column 'National Rate Raw'
		dataType: string
		sourceColumn: national_rate_raw

	column 'Footnote Code'
		dataType: string
		sourceColumn: footnote_code_raw

	partition 'Fact National Benchmark' = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        File.Contents("C:\Users\10619\Documents\Projects\provider-payer-quality-reporting\data\processed\powerbi_import\fact_provider_national_benchmark.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    PromotedHeaders = Table.PromoteHeaders(
				        Source,
				        [PromoteAllScalars=true]
				    ),
				    TypedColumns = Table.TransformColumnTypes(
				        PromotedHeaders,
				        {{"national_benchmark_key", Int64.Type}, {"measure_key", Int64.Type}, {"reporting_period_key", Int64.Type}, {"source_release_key", Int64.Type}, {"national_rate_numeric", type number}, {"national_rate_raw", type text}, {"footnote_code_raw", type text}},
				        "en-US"
				    )
				in
				    TypedColumns

